export const _1 = 
[
"Indian classical dance techniques like Rasa and Bhava trace their origins to . - Bharatmuni's Natyashastra.",
"Lavani, Powada, Koli, Waghya Murali and Dhangari Gaja are folk dance from . - Maharashtra.",
"One act play of Sattriya is called . - Ankiya Nat.",
"The origin of most of the classical dance forms of India is from . - Natya Shastra.",
"The dance form of Goa which is known as 'Warrior Dance' . - Ghode Modni.",
"Manipuri dance is based on Rasleela themes of . - Radha and Krishna.",
"Sattriya (Assam) was recognised as a Classical dance by the Sangeet Natak Akademi in . - 2000.",
"UNESCO recognized 'Mudiyettu,' a ritual-drama of Kerala as an 'intangible cultural heritage of humanity in . - 2010.",
"Thullal dance is originated from . - Kerala.",
"The 'Ka Shad Mastieh' or victory dance of the Khasi tribe is from . - Meghalaya.",
"Maimata is a popular folk dance of . - Tripura.",
"Bharatanatyam dance is traditionally performed in . - Carnatic music.",
"Thumri music is associated with . - Kathak (Uttar Pradesh).",
"The masculine aspect of the Manipuri classical dance is known as . - Choloms.",
"Kathakali dance was immediately preceded by a practice session called . - Sevakali.",
"The abhinayas that deals with the use of costumes, jewellery, facial make-up etc . - Aharya Abhinaya.",
"Siddhis have a cultural history in Gujarat for about 300 years, known for their unique dance called . - Siddhi Dhamal.",
"Natwari Nritya is associated with . - Kathak Dance.",
"The Dandari-Gusadi festival is celebrated by the tribe . - Raj Gond and Kolams.",
"Paika dance of Jharkhand performed (male member) by . - Munda tribe.",
"Gaur Maria, is a dance form from . - Chhattisgarh.",
"Lebang Boomani dance is the harvest dance of . - Tripura.",
"Bharatanatyam was banned by the British government in . - 1910.",
"The victory of truth over falsehood celebrates in Maharashtra through . - Songi Mukhawate dance.",
"The Songi Mukhawate dance is of . - Maharashtra.",
"Songi Mukhawate dance represent Narasimha, an aspect of . - Lord Vishnu.",
"Rikham pada dance belongs to . - Arunachal Pradesh.",
"'The soft and suitable for female presentation' known as . - Laasya.",
"The Indian classical dances have two basic aspects . - Laasya and Tandav.",
"The word 'Kathak' is derived from . - Story.",
"The technique of classical dancing was codified in 5th century B.C by . - Bharata.",
"The Lambadi dance is a folk dance form of the . - Banjara tribe.",
"Kalbelia (Snake Charmer Dance) is a famous folk dance of . - Rajasthan.",
"Kalbelia dance is performed by the . - Kalbelia Community.",
"The Balti dance is related to the state of . - Ladakh.",
"Conveying the meaning through body movements is known as . - Angika Abhinaya.",
"Mundari dance of Munda tribe is associated with . - Jharkhand.",
"Tapu dance performed by Adi tribe of . - Arunachal Pradesh.",
"Chali, Jhumura and Nadu Bhangi are form of . - Sattriya Classical dance.",
"Dhimsa folk dance is performed by Porja tribes of . - Araku valley (Andhra Pradesh).",
"Kandyan is a traditional dance form of . - Sri Lanka.",
"Trippani, Hudo, Mer Ras, Palli Jag Garbo are folk dances of . - Gujarat.",
"Kathak dance is associated with . - Hindustani classical music.",
"Gair folk dance is performed by bhil community in the state of . - Rajasthan.",
"‘Nat’ is the traditional singing style which is associated with . - Manipuri dance.",
"Ras, Sankirtana and Thang-Ta are the popular forms of . - Manipuri dance.",
"The earliest form of Manipuri dance is . - Lai Haraoba.",
"Dollu Kunitha , Bhoota and Balakat dances are associated with state of . - Karnataka.",
"Drums are adorned with colourful clothes in the dance of . - Dollu Kunitha.",
"Laho dance is performed by Jaintiya tribe of . - Meghalaya.",
"Paika dance is performed by Munda tribe in the region of . - Chota Nagpur Plateau.",
"Chavittu Kali dance is associated with the state of . - Kerala.",
"Gugga folk dance is performed by men in . - Haryana.",
"Tevitichiyattam, Nangai Natakam and Dasiyattam are the forms of . - Mohiniyattam dance.",
"Garba, Dandiya Raas, Tippani Juriun dances are popular in state of . - Gujarat.",
"'Sarhul' festival of dance performed in Jharkhand, by . - Oraon tribe.",
"Jagoi and Thabal Chongba are the famous dances of . - Manipur.",
"Seraikella Chhau is a popular dance form of . - Jharkhand.",
"Ghurehi folk dance is performed (by women) in the region of . - Himachal Pradesh.",
"The Chari folk dance is primarily performed (by women) in . - Rajasthan.",
"Kamsale is the folk dance of . - Karnataka.",
"Padayani folk dance performed at Bhadrakali temple in . - Kerala.",
"The bamboo dance of Mizoram is called . - Cheraw dance.",
"The Princely states was primarily associated with Kathak . - Avadh.",
"The Pakhawaj syllables are used to conclude the classical dance of . - Odissi.",
"The dance that features painted masks, big skirts, heavy jackets, lots of jewellery, and tall headdresses is . - Kathakali.",
"The dance where dancers forms a counterclockwise circle with concentric circles in opposite directions . - Garba dance.",
"Kuchipudi, a Yakshagaana style, conceived by Siddhendra Yogi in . - 17th century.",
"The number of Indian classical dance forms recognized by the Sangeet Natak Academy of India is . - 8.",
"Jhijhiya dance is performed to please the god of rain ‘Indra’ for good rain and crop in . - Bihar.",
"The tribe who performs the Bagurumba folk dance in assam . - Bodo tribe.",
"Grida folk dance is performed in . - Madhya Pradesh.",
"‘Gonph’ is a famous folk dance of . - Goa.",
"Kud, a folk dance, is associated with . - Jammu and Kashmir.",
"Chang Lo tribal dance is performed by the Chang tribe of . - Nagaland.",
"Gunakanta Dutta Borbyan was awarded the Sangeet Natak Akademi Award in . - Sattriya dance.",
"Fugdi dances is performed in . - Goa.",
"Tashi Sabdo dance is associated with . - Sikkim.",
"Agni, Mardana Jhumar, Phagua dances are associated with . - Jharkhand.",
"Koli is the folk dance of . - Maharashtra and Goa.",
"The folk dance ‘Lambadi’ is associated with . - Andhra Pradesh.",
"Chu Faat is a folk dance of . - Sikkim."
]
export const _2 = 
[
  
    
      " Zo Mal Lok dance is associated with - Sikkim.",
      " Mohiniyattam dance is performed by women in honour of - Lord Vishnu.",
      " Gotipua, dance of Odisha, performed in honour of - Lord Jagannath.",
      " Bhama Kalapam is the classical dance-drama associated with - Kuchipudi.",
      " Saila, Panthi, Pandwani, Raut Nacha dances are associated with - Chhattisgarh.",
      " Ghodemodini is folk dance of - Goa.",
      " Choliya, a martial dance is related to - Uttarakhand.",
      " The prime themes of Kathak are tied with - Vaishnavism.",
      " Bhangra, Luddi, Giddha are folk dances of - Punjab.",
      " Jagoi and Cholom are the two main divisions of - Manipuri dance.",
      " Satriya dance of Assam is inspired by - Bhakti movement.",
      " The classical work 'Hastalakshan Deepika' is related to the dance - Kathakali.",
      " Matki dance is performed in - Madhya Pradesh.",
      " Gugga, Khoria, and Phag dances are associated with - Haryana.",
      " Hurka Baul dance, performed during maize and paddy cultivation in - Uttarakhand.",
      " Kummi dance is associated with - Tamil Nadu.",
      " Cheraw is a folk dance associated with - Mizoram.",
      " Bharatanatyam was originally known as - Sadir Attam.",
      " Gotipua is a traditional dance form in - Odisha.",
      " Hand gestures in Mohiniyattam which are mainly adopted from Hastalakshana Deepika text are - 24.",
      " Gavari, a dance-drama is majorly performed in - Rajasthan.",
      " Purulia, Mayurbhanj, Seraikella are subtypes of the dance - Chhau.",
      " Charu Sija Mathur is a name that is synonymous with - Manipuri dance.",
      " Kolannalu, a folk dance is popularly known as - stick dance.",
      " Wangla is a famous folk dance of - Meghalaya.",
      " Bharatanatyam dance evolved from - 'Ekaharya Lasyanga'.",
      " Konark dance festival is organized every year for 5 days in - Odisha.",
      " Varnam is one of the stages in the classical dance of - Bharatanatyam.",
      " The Khajuraho Dance Festival was started by the Government of India in collaboration with Madhya Pradesh Kala Parishad in - 1975.",
      " The Khon, the masked drama dance performance depicting the glory of Lord Rama is associated with - Thailand.",
      " Theyyam is the ritual art form of - Kerala.",
      " Veera Natyam is a ritual dance form of - Andhra Pradesh.",
      " Lotia is the regional music of - Rajasthan.",
      " A form of folk theatre which is based on the life of Lord Krishna is - Raasleela.",
      " Yakshagana folk dance is associated with - Karnataka.",
      " Chhau dance was inscribed in the UNESCO Intangible Cultural Heritage List in - 2010.",
      " Buddhist chanting of Ladakh was inscribed in the UNESCO Intangible Cultural Heritage List in - 2012.",
      " Tradition of Vedic chanting was inscribed in the UNESCO Intangible Cultural Heritage List in - 2008.",
      " A freestyle dance where performers dance with clay pots filled with burning incense is - Dhunuchi Naach.",
      " Ancient dance teachers or gurus of Bharatanatyam are popularly known as - Nattuvanars.",
      " Veedhi-Bhagavatam is a famous dance form of - Andhra Pradesh.",
      " Lavani is a folk dance of - Maharashtra.",
      " Hand gestures used in Indian classical dances are called - Mudra.",
      " Ghoomar is traditionally performed by - Bhil tribe (Rajasthan).",
      " Mayurbhanj Chau dance is performed in - Odisha.",
      " Purulia Chau dance is performed in - West Bengal.",
      " The Ras Leela was first started as a dance form in 1779 by - Bhagyachandra (Meitei monarch).",
      " Danda-nacha (a dance form of Odisha) narrates about the story of - Lord Shiva.",
      " Gaur Maria dance belongs to - Chhattisgarh.",
      " The element in Kuchipudi dance in which the performer balances his feet on the edge of a brass plate - Tarangam.",
      " The competitive play between dancer and tabla player in Kathak is - Jugalbandi.",
      " Rasa in which Love can be best expressed is - Shringaara rasa.",
      " Mudiyettu is a ritual dance drama from Kerala based on the mythological tale of a battle between - Goddess Kali and Demon Darika.",
      " According to 'Natya Shastra', Mohiniyattam is a form of - Lasya Dance.",
      " Mohiniyattam dance emotes a play through dancing and singing where the song is customarily in - Manipravala language.",
      " A dance form of Nagaland which is performed as preparation for a hunting expedition, known as - Sadal Kekai.",
      " The dance movement characterized by bent legs while feet keep rhythm are present in - Bharatanatyam.",
      " The classical dance style which is inscribed on the Gopuram of Chidambaram temple - Bharatanatyam.",
      " Bharatanatyam expresses South Indian religious themes and spiritual ideas of - Shaivism.",
      " Daskathia is the tribal dance of - Odisha.",
      " Dance performed by the Santhal tribe of Jharkhand - Jhika Dashain.",
      " Changai dance is associated with - Nagaland.",
      " Alarippu is a dance piece from - Bharatnatyam.",
      " Thabal Chongba is a folk dance of - Manipur.",
      " Bhavai (Vesha or Swang) is the popular folk theatre form of - Gujarat.",
      " Paika, Ghumra and Dhap are the folk dances of - Odisha.",
      " The Raigarh Gharana is associated with - Kathak.",
      " Jamda folk dance is associated with - Jharkhand.",
      " Kalasam is a dance sequence in - Kathakali.",
      " Kajari is a folk song and dance which originated in - Uttar Pradesh.",
      " Chhau dance exists in - 3 main styles (Saraikela - Jharkhand, Mayurbhanj - Orissa, and Purulia - West Bengal).",
      " Kalakshetra style is associated with - Bharatanatyam.",
      " Kud is a folk dance of - Jammu and Kashmir.",
      " Theoretical foundations of Bharatanatyam have been found in - Natya Shastra.",
      " Vazhuvoor is one of the styles in - Bharatanatyam.",
      " Luddi is a folk dance of - Punjab.",
      " Ras-Lila recognised as classical dance form of - Manipuri.",
      " Oldest gharana of Kathak Dance - Banaras Gharana. Gharanas of Kathak - Jaipur, Lucknow, Benaras and Raigarh.",
      " Bhortal dance is famous in - Assam.",
      " Lai Haraoba is the earliest form of - Manipuri dance.",
      " The Joenpa Legso is a welcome dance of - Bhutan.",
      " Mati-Akhora is associated with - Sattriya dance.",
      " The Nalacharitham play is associated with - Kathakali.",
      " Dance performed by the Kamar tribe of Madhya Pradesh is - Terah Tali."
    ]
    
    


 export const _3  = [
      "Traditional dance mainly performed during Navratri .- Garba.",
      "Dance form related to the worship of Lord Jagannath .- Odissi.",
      "Classical dance form which begins with a drum playing performance called Kelikottu .- Kathakali.",
      "Zang Talam is a popular dance of Mizoram performed by .- Paihte tribe.",
      "Gair dance is performed by the .- Bhil community of Rajasthan.",
      "Karagam Folk Dance is associated with .- Tamil Nadu.",
      "Bhoota Kola is a spirit worship ritual dance of .- Karnataka.",
      "Suggi is a famous folk dance form of .- Karnataka.",
      "Dance performed in the temples of Tamil Nadu, by the Devadasis .- Bharatanatyam (Dasiattam).",
      "Sapera dance of Rajasthan is also known as .- Kalbelia dance.",
      "Ekaharya, where one dancer performs many roles in a single performance is associated with .- Bharatanatyam.",
      "Jagoi and Cholom are the two main divisions in .- Manipuri Dance.",
      "Kathakali took shape in Southern India in the 17th century under the patronage of the .- Prince of Karnataka.",
      "Dance performed at the time of Dussehra in Mithila region (Bihar) is .- Jhijhiya.",
      "Sangphao tribal dance is performed in .- Arunachal Pradesh.",
      "The Tapu dance from Arunachal Pradesh is performed by .- Adi Tribe.",
      "Charkula is a famous dance form associated with .- Uttar Pradesh.",
      "Dance performed during the worship of Murugan the Hindu God of war .- Kavadi attam.",
      "Rouf is a folk dance of .- Jammu and Kashmir.",
      "The Main theme of Manipuri dance is .- Devotion.",
      "Panthi dance form is associated with .- Chhattisgarh.",
      "The gopurams of the Chidambaram temple (Tamil Nadu) depict the poses of .- Bharatanatyam.",
      "Ghoomar is a folk dance of .- Rajasthan.",
      "Kuchipudi dance is accompanied by .- Carnatic music.",
      "The music of Bharatanatyam belongs to .- Carnatic System.",
      "After recovering from smallpox, a typical dance performed in West Bengal is .- Brita dance.",
      "Colorful makeup and unique masks depicting the ancient martial art of .- Kathakali.",
      "Hai - Hak Dance is associated with .- Tripura.",
      "Gugga dance is a traditional folk dance of .- Haryana.",
      "The Zo-Mal -Lok dance is associated with .- Lepcha community (Sikkim).",
      "Dance that developed from the Vaishnavite monasteries of Assam .- Sattriya.",
      "Dance in which the artist never establishes eye contact with the audience .- Manipuri.",
      "Dance performed by the women of Maharashtra is .- Lavani.",
      "The folk dance Tarangamel is associated with .- Goa.",
      "Buiya Dance form is associated with the state of .- Arunachal Pradesh.",
      "Classical dance form which uses various colours on face to symbolise the characters is .- Kathakali.",
      "Dance form which is mentioned in the ancient text of Vyavahar Mala .- Mohiniyattam.",
      "Dhaman is a dance form associated with the state of .- Himachal Pradesh.",
      "Rangabati is a folk dance of .- Odisha.",
      "Nupa dance is associated with .- Manipur.",
      "Borgeet, a musical composition, is used in .- Sattriya dance.",
      "The traditional folk dance of Rajasthan, performed by Kanjar tribe is .- Chakri.",
      "Mundari is a famous dance of .- Jharkhand.",
      "Zangtalam, Chailam, Cheraw dance belong to .- Mizoram.",
      "The folk dance Hojagiri is associated with .- North-East India.",
      "Mohiniyattam is associated with .- God Vishnu.",
      "Kathakali is associated with .- God Krishna.",
      "Ghoomar dance form was developed by Bhil tribes to worship .- Goddess Saraswati.",
      "The main percussion instrument used in the performance of Mohiniyattam dance is .- Edakka.",
      "Classical dance which referred to as the dance of the storytellers .- Kathak.",
      "Folk dance that represents a mock fight between Goddess Durga and Mahishasura .- Dandiya Raas.",
      "A dance form influenced by Bihu dance .- Sattriya.",
      "Dance of Jharkhand performed mainly by the tribal women during the cultivation season .- Janani-Jhumur.",
      "Dance form of Assam performed by the 'Kulis' (people who work in the tea gardens) during autumn .- Jhumur.",
      "The drum prominently used as a part of dance movements in .- Pung Cholom (Manipuri).",
      "Dance form which depicts the anguish of women whose partners are gone from home .- Biraha.",
      "Gatka, a traditional fighting style of the Nihang Sikh warriors has originated from .- Punjab.",
      "Mudiyettu is a traditional folk theatre form of .- Kerala.",
      "Elelakkaradi is a tribal dance form of .- Kerala.",
      "Waghya Murali dance, associated with Lord Khandoba, originated in .- Maharashtra.",
      "Sangrai is a folk dance of .- Tripura.",
      "Dance dedicated to temples and was earlier known as Sadir .- Bharatanatyam.",
      "First of India's traditional dance to be refashioned as a theatre art .- Bharatanatyam.",
      "Dance associated with the Vaishnavism of the Meitai people .- Manipuri Dance.",
      "Ummatt-aat is a folk dance form performed in .- Coorg (Karnataka).",
      "Bharatnatyam dance recital is done by .- Nattuvanar.",
      "Lava is a Popular folk dance of .- Minicoy Island.",
      "A popular mask dance of South Malabar .- Kummattikali.",
      "Chairs on heads with lighted diyas are performed by women in which dance .- Chari Dance.",
      "Dance which combines speech, mime and pure dance .- Kuchipudi.",
      "The Veeragase dance, performed during the Dussehra festival belongs to .- Karnataka.",
      "Rathwa ni Gher is a dance performed on the occasion of Holi by the Rathwa tribe of .- Gujarat.",
      "Ratvai is a dance form associated with the .- Mewati tribes.",
      "Tillana style is associated with .- Bharatanatyam.",
      "Chad Sukra, a popular traditional dance festival of Meghalaya, is celebrated as a .- Sowing festival.",
      "Community of Sikkim that is traditionally associated with the folk dance Chu-Faat .- Lepcha Community.",
      "Jawaharlal Nehru Manipur Dance Academy is located in .- Imphal.",
      "Kamsale is a dance form traditional to the state of .- Karnataka.",
      "Rikhampada is a traditional dance of .- Arunachal Pradesh.",
      "Dance form in Mizoram participated exclusively by village guests .- Khuallam.",
      "A folk dance of Odisha depicting the life of Lord Krishna in .- Ranpa dance."
    ]
    
    export const _4= [
      "Mangalacharan, Sthayee, Pallavi, Abhinaya and Mokshya are items of. - Odissi Dance.",
      "Maimata is a popular dance of the Kaloi community from the state of. - Tripura.",
      "Bhand Pather is the dance form of. - Kashmir.",
      "Aaluyattu is a folk-dance form from the state of. - Nagaland.",
      "Bolak-aat dance form belongs to. - Karnataka.",
      "Hallisaka is a group dance native to. - Gujarat.",
      "Birhor dance is a tribal folk dance of. - Jharkhand.",
      "Kadsa is a kalasha carrying dance style performed by women in. - Jharkhand.",
      "A dance which is harmonious combination of five fine art forms. - Kathakali.",
      "Kolkali is popular dance form of. - Lakshadweep Island.",
      "Saila dance performed by boys after the harvest season in. - Chhattisgarh.",
      "The 'Royal Dance of Ladakh' is. - Shondol.",
      "Dangi is a folk Dance of. - Himachal Pradesh.",
      "Dalkhai is the folk dance of. - Odisha.",
      "Mayurbhanj Chhau dance is native to. - Odisha.",
      "Padayani is a ritual dance art form performed at Bhadrakali temple in. - Kerala.",
      "Garadi folk dance (related to the Ramayana) in Puducherry is performed at. - Villianur Temple.",
      "Siddi Dhamal Dance is associated with. - Gujarat.",
      "’Alkap' is a traditional dance-drama found in Jharkhand and. - West Bengal.",
      "‘Huli Vesha’ is a popular folk dance in. - Karnataka.",
      "Harvest dance which is popular in the Bundelkhand region of Madhya Pradesh. - Jawara.",
      "Rai is primarily a folk dance of. - Madhya Pradesh.",
      "A dance in Andhra Pradesh similar to the stick dance is. - Kolannalu.",
      "Paika Dance is famous in. - Odisha.",
      "Rengma is primarily a folk dance of. - Nagaland.",
      "The Sattriya dance was introduced in 15th century A.D. by saint. - Mahapurusha Sankaradeva.",
      "Thang Ta is an exclusive Martial dance form of. - Manipur.",
      "A folk art performed in the North Malabar region of Kerala is. - Kolkali.",
      "A folk dance in Himachal Pradesh that ends with a Yagya. - Nati.",
      "The Khajuraho Dance Festival was instituted in. - 1975.",
      "The Khajuraho dance festival was instituted by the collaboration between Government of India and. - Madhya Pradesh Kala Parishad.",
      "Bharatanatyam is classical dance form of. - Tamil Nadu.",
      "Two classical dances of Kerala. - Kathakali & Mohiniattam.",
      "Kuchipudi, a classical dance originated in. - Andhra Pradesh.",
      "Manipuri is classical dance belongs to. - Manipur.",
      "Kathak is classical dance form of. - Uttar Pradesh.",
      "Classical dance of Odisha. - Odissi.",
      "Sattriya, a classical dance from. - Assam.",
      "Changsang dance is performed by the Chang tribe from Nagaland during. - Naknyulum festivals.",
      "Rechungma, Gha To Kito, and Chi Rmu are the dance forms of. - Sikkim.",
      "Jat-Jatin is a popular folk dance of. - Bihar.",
      "Bharatnatyam dance was revealed by Lord Brahma to sage Bharata, who codified this dance in. - Natya Shastra.",
      "Hurkiya Baul is a folk dance of. - Uttarakhand.",
      "Bardo Chham is folk dance of. - Arunachal Pradesh.",
      "Gaur Maria is folk dance of. - Chhattisgarh.",
      "Dandiya dance is associated with. - Gujarat.",
      "Dhalo is a Popular ritual folk dance of. - Goa.",
      "The Gambhira dance performed using various wooden masks in. - West Bengal.",
      "Mando is a folk dance of. - Goa.",
      "The traditional theatre of Kerala where 8 plays are performed for 8 consecutive days. - Krishnanattam.",
      "The only Indian dance form featured in Michael Jackson's 1991 music video 'Black or White’. - Odissi.",
      "The Sikkimese are known for their amazing mask dance, known as. - Chaam.",
      "A Classical dance which in its present form is influenced by Mughal tradition. - Kathak.",
      "Dumhal dance form belongs to. - Jammu & Kashmir.",
      "The dance form ‘Chharhi’ has originated from. - Himachal Pradesh.",
      "The Mathuri folk dance is practised in. - Telangana.",
      "Nat Puja, Bihu, and Chongli are folk dances of. - Assam.",
      "A popular folk dance of Nimar region of Madhya Pradesh. - Kathi.",
      "Choliya dance form is associated with. - Uttrakhand.",
      "Spao Dance belongs to. - Ladakh.",
      "Cheraw (bamboo Dance) belongs to. - Mizoram.",
      "A south Indian classical dance form which means ‘Story-Play’. - Kathakali.",
      "The Indian dance form ‘Manipuri’ is mostly based on the themes of. - Krishna-Gopis.",
      "Tapali & Dagla are the folk dance of. - Chhattisgarh.",
      "Raut Nacha is a famous tribal dance of. - Chhattisgarh.",
      "Parichakali is a popular folk dance of. - Lakshadweep.",
      "The Kajri folk dance of Uttar Pradesh is related to season of. - Monsoon.",
      "Maruni Dance is associated with. - Sikkim.",
      "Dance performed by young boys in Odisha refers to the. - ‘Gotipua’.",
      "’Dollu Kunitha’ (folk dance) is from. - Karnataka.",
      "The performers wear a cylindrical skirt named 'PotIoi’ in. - Manipuri dance.",
      "Triangle mudra is associated with dance form. - Odissi.",
      "Laho is a dance of. - Meghalaya.",
      "Jhali is the folk dance of. - Himachal Pradesh.",
      "’Deodhani’ dance of Assam is associated with the. - Snake goddess Manasa.",
      "Mayilattam (the dance of South India) is also called. - Peacock dance.",
      "Natpuja is a folk dance of. - Assam.",
      "Mahari dance style is a dance form of. - Odissi dance.",
      "The Hunta dance of Jharkhand is associated with. - Santhal tribal community.",
      "Manipuri dance often depicts scenes from the life of. - Lord Krishna.",
      "‘Mohiniyattam’ means. - Dance of the Enchantress.",
      "Dollu Kunitha, a folk dance of Karnataka, is performed for. - Lord Shiva.",
      "’Tippani’ is a well-known dance of. - Gujarat.",
      "The gestures used in Bharatnatyam are known as. - Mudras.",
      "The Gopurams of the Chidambaram temple contain numerous poses of. - Bharatanatyam.",
      "‘Jhora’ dance is performed as a springtime celebration in. - Uttarakhand.",
      "The Hindu god associated with Mohiniyattam dance is. - Lord Vishnu.",
      "The musical instrument used in the Mohiniyattam dance is. - Edakka.",
      "The classical dance of storytellers is. - Kathak.",
      "The Sattriya dance form was introduced by. - Mahapurusha Sankaradeva."
    ];
    export const _5 = [
      "Kalbelia is a folk-dance of. - Rajasthan.",
      "A folk dance that represents a mock fight between Goddess Durga and Mahishasura is. - Dandiya Raas.",
      "Sattriya dance forms is influenced by. - Bihu dance.",
      "Dance of Jharkhand that performed mainly by the tribal women during the cultivation season. - Janani-Jhumur.",
      "The dance drama Bhamakalapam based on Kuchipudi was composed by. - Siddhendra Yogi.",
      "Garba and Dandiya are popular folk dances of Gujarat are performed during. - Navratri.",
      "A dance style called 'Hi-Dance' was created by. - Uday Shankar.",
      "The dance of Assam that performed by 'Kulis' during autumn is. - Jhumur Dance.",
      "'Dhimsa' is a folk dance of. - Andhra Pradesh.",
      "Lavani is a popular dance of. - Maharashtra.",
      "The Tapu dance is performed in. - Arunachal Pradesh.",
      "'Karagam' is a folk dance of. - Tamil Nadu.",
      "Bhadam dance is popular among. - Bharia tribe.",
      "'Saila' is a folk dance which is performed with bamboo sticks in. - Chhattisgarh.",
      "’Ahirai’ is a folk dance of the Bharia tribe of. - Madhya Pradesh.",
      "‘Fugdi’ is a folk dance of. - Goa.",
      "’Fugdi’ is celebrated in the month of. - Bhadrapad.",
      "’Fugdi’ is celebrated by the. - Konkan women.",
      "Bhagoriya dance is performed by Bhils in. - Madhya Pradesh.",
      "Cheraw dance is the traditional bamboo dance of. - Mizoram.",
      "Yakshagana is a traditional theatre, developed in. - Karnataka.",
      "A sword dance that depict the martial art tradition of the Kumaoni tribe is. - Chholiya dance.",
      "The Lebang Boomani Dance is the harvest dance of. - Tripura.",
      "Aji Lamu is a folk dance of. - Arunachal Pradesh.",
      "Aji Lamu is a folk dance performed by. - Monpa Tribes.",
      "Chang Lo Dance performed by Chang tribe of. - Nagaland.",
      "Jagoi is the famous dance form of. - Manipur.",
      "'Laho' is a popular dance of. - Meghalaya.",
      "Kharaiti is a martial dance performed with swords in. - Himachal Pradesh.",
      "Chutki is the traditional dance form of. - Sikkim.",
      "‘Khuallam’ is a folk dance of. - Mizoram.",
      "Hurka Baul is a famous dance of. - Uttrakhand.",
      "Goddess Amba is the presiding deity of. - Bhavai dance.",
      "‘Grida’ is a folk dance of. - Madhya Pradesh.",
      "Bhavai is a folk dance of. - Rajasthan.",
      "The dance which involves balancing pots on the head of the dancer. - Bhavai dance.",
      "Paika Dance performed by a tribal community of. - Jharkhand.",
      "Folk dances which is performed holding a sword in one hand and a shield in the other. - Paika Dance.",
      "Mundari dance is associated with. - Jharkhand.",
      "’Fag’ is a folk dance associated with. - Haryana.",
      "Cham Mask dance is celebrated in. - Bhutan.",
      "Dhangar is the worship dance form of. - Goa.",
      "Gotipua is a folk dance of. - Odisha.",
      "Chau dance forms has been included in the UNESCO Heritage Dances in. - 2010.",
      "Suwa folk dance is associated with. - Chhattisgarh.",
      "While performing the Suwa folk dance women act like the bird. - Parrot.",
      "’Ponung’ is a folk dance associated with. - Arunachal Pradesh.",
      "Dumhal is a famous folk dance of. - Jammu and Kashmir.",
      "'Manduka Shabdam, a story of the frog, is performed in. - Kuchipudi dance.",
      "Bagurumba is a group dance performed by the people of. - Bodo community.",
      "Jhijhiya is a famous cultural dance of. - Bihar.",
      "\"Tamasha\" is a folk dance of. - Maharashtra.",
      "Karakattam is a traditional dance of. - Tamil Nadu.",
      "Maruni dance is a group dance of the Nepali community in. - Sikkim.",
      "Scenes of Lord Krishna are performed in. - Manipuri dance.",
      "Jat-Jatin, Bidesia, Jhijhiya are dance form of. - Bihar.",
      "'Zeliang' is a tribal folk dance of. - Nagaland.",
      "‘Shondol’ is a dance form of. - Ladakh.",
      "Hojagiri dance is a tribal dance form of the Reang community associated with. - Tripura.",
      "Kuchipudi dance was composed by Vaishnava poet. - Sidendra Yogi.",
      "Ghoomar is the traditional folk dance of. - Rajasthan.",
      "Bharatanatyam traces its lineage to the ancient dance of. - Sadir Attam.",
      "Mukhota dance is usually performed to worship God Bhumitayal in. - Uttarakhand.",
      "Kathak in its present form has the influence of. - Mughal tradition.",
      "Dhimsa is a folk dance of. - Andhra Pradesh.",
      "Dhimsa is a tribal dance form that is performed by. - Porja caste women.",
      "Bhand Pather theater is a tradition primarily of. - Jammu and Kashmir.",
      "Hallisaka is a group dance native to. - Gujarat.",
      "Birhor dance is a tribal folk dance from. - Jharkhand.",
      "Kadsa dance is a dance style performed carrying a. - ‘Kalasha’.",
      "Bhootada Kola is a spiritual folk dance of. - Karnataka.",
      "‘Leshalaptu’ is a dance form of. - Nagaland.",
      "Ponung is a folk dance form of. - Arunachal Pradesh.",
      "Chhau, Kalaripayattu, Lazim are traditional dances of. - Martial art form.",
      "Cheraw is a traditional dance form of. - Mizoram.",
      "‘Rauf’ is a folk dance associated with. - Jammu and Kashmir.",
      "Bayalata is a dance form of. - Karnataka.",
      "Jhulan is a folk dance form of. - Rajasthan.",
      "Popir is a dance form of. - Arunachal Pradesh.",
      "Panthi is a dance form of. - Chhattisgarh.",
      "The Dhangar dance is performed by shepherd community of Goa. - during Navratri.",
      "Karma is a dance form of. - Jharkhand.",
      "Nati folk dances, India has made its entry in the Guinness Book of World Records in. - 2015.",
      "Pung Cholam is a dance form of. - Manipur.",
      "Lai Haroba festival is a part of. - Manipuri dance.",
      "Giddha is a folk dance form of. - Punjab.",
      "Tertali is a dance form of. - Rajasthan.",
      "Bihu is folk dance form of. - Assam.",
      "Sonal Mansingh is a famous. - Odissi dancer.",
      "Jatra folk theatre of. - Eastern India.",
      "Gair is a folk dance form of. - Rajasthan.",
      "The folk dance which is prevalent on the occasion of Deepawali in the regional areas of Sagar. - Moniya Dance.",
      "The Turra-Kalangi folk drama is famous in. - Nimar region (Madhya Pradesh).",
      "In Rajasthan, Agni dance (Fire dance) is performed by. - Jasnathi Siddha Sect."
    ];
    