export const _1 = 
[
"Indian classical dance techniques like Rasa and Bhava trace their origins to . - Bharatmuni's Natyashastra.",
"Lavani, Powada, Koli, Waghya Murali and Dhangari Gaja are folk dance from . - Maharashtra.",
"One act play of Sattriya is called . - Ankiya Nat.",
"The origin of most of the classical dance forms of India is from . - Natya Shastra.",
"The dance form of Goa which is known as 'Warrior Dance' . - Ghode Modni.",
"Manipuri dance is based on Rasleela themes of . - Radha and Krishna.",
"Sattriya (Assam) was recognised as a Classical dance by the Sangeet Natak Akademi in . - 2000.",
"UNESCO recognized 'Mudiyettu,' a ritual-drama of Kerala as an 'intangible cultural heritage of humanity in . - 2010.",
"Thullal dance is originated from . - Kerala.",
"The 'Ka Shad Mastieh' or victory dance of the Khasi tribe is from . - Meghalaya.",
"Maimata is a popular folk dance of . - Tripura.",
"Bharatanatyam dance is traditionally performed in . - Carnatic music.",
"Thumri music is associated with . - Kathak (Uttar Pradesh).",
"The masculine aspect of the Manipuri classical dance is known as . - Choloms.",
"Kathakali dance was immediately preceded by a practice session called . - Sevakali.",
"The abhinayas that deals with the use of costumes, jewellery, facial make-up etc . - Aharya Abhinaya.",
"Siddhis have a cultural history in Gujarat for about 300 years, known for their unique dance called . - Siddhi Dhamal.",
"Natwari Nritya is associated with . - Kathak Dance.",
"The Dandari-Gusadi festival is celebrated by the tribe . - Raj Gond and Kolams.",
"Paika dance of Jharkhand performed (male member) by . - Munda tribe.",
"Gaur Maria, is a dance form from . - Chhattisgarh.",
"Lebang Boomani dance is the harvest dance of . - Tripura.",
"Bharatanatyam was banned by the British government in . - 1910.",
"The victory of truth over falsehood celebrates in Maharashtra through . - Songi Mukhawate dance.",
"The Songi Mukhawate dance is of . - Maharashtra.",
"Songi Mukhawate dance represent Narasimha, an aspect of . - Lord Vishnu.",
"Rikham pada dance belongs to . - Arunachal Pradesh.",
"'The soft and suitable for female presentation' known as . - Laasya.",
"The Indian classical dances have two basic aspects . - Laasya and Tandav.",
"The word 'Kathak' is derived from . - Story.",
"The technique of classical dancing was codified in 5th century B.C by . - Bharata.",
"The Lambadi dance is a folk dance form of the . - Banjara tribe.",
"Kalbelia (Snake Charmer Dance) is a famous folk dance of . - Rajasthan.",
"Kalbelia dance is performed by the . - Kalbelia Community.",
"The Balti dance is related to the state of . - Ladakh.",
"Conveying the meaning through body movements is known as . - Angika Abhinaya.",
"Mundari dance of Munda tribe is associated with . - Jharkhand.",
"Tapu dance performed by Adi tribe of . - Arunachal Pradesh.",
"Chali, Jhumura and Nadu Bhangi are form of . - Sattriya Classical dance.",
"Dhimsa folk dance is performed by Porja tribes of . - Araku valley (Andhra Pradesh).",
"Kandyan is a traditional dance form of . - Sri Lanka.",
"Trippani, Hudo, Mer Ras, Palli Jag Garbo are folk dances of . - Gujarat.",
"Kathak dance is associated with . - Hindustani classical music.",
"Gair folk dance is performed by bhil community in the state of . - Rajasthan.",
"‘Nat’ is the traditional singing style which is associated with . - Manipuri dance.",
"Ras, Sankirtana and Thang-Ta are the popular forms of . - Manipuri dance.",
"The earliest form of Manipuri dance is . - Lai Haraoba.",
"Dollu Kunitha , Bhoota and Balakat dances are associated with state of . - Karnataka.",
"Drums are adorned with colourful clothes in the dance of . - Dollu Kunitha.",
"Laho dance is performed by Jaintiya tribe of . - Meghalaya.",
"Paika dance is performed by Munda tribe in the region of . - Chota Nagpur Plateau.",
"Chavittu Kali dance is associated with the state of . - Kerala.",
"Gugga folk dance is performed by men in . - Haryana.",
"Tevitichiyattam, Nangai Natakam and Dasiyattam are the forms of . - Mohiniyattam dance.",
"Garba, Dandiya Raas, Tippani Juriun dances are popular in state of . - Gujarat.",
"'Sarhul' festival of dance performed in Jharkhand, by . - Oraon tribe.",
"Jagoi and Thabal Chongba are the famous dances of . - Manipur.",
"Seraikella Chhau is a popular dance form of . - Jharkhand.",
"Ghurehi folk dance is performed (by women) in the region of . - Himachal Pradesh.",
"The Chari folk dance is primarily performed (by women) in . - Rajasthan.",
"Kamsale is the folk dance of . - Karnataka.",
"Padayani folk dance performed at Bhadrakali temple in . - Kerala.",
"The bamboo dance of Mizoram is called . - Cheraw dance.",
"The Princely states was primarily associated with Kathak . - Avadh.",
"The Pakhawaj syllables are used to conclude the classical dance of . - Odissi.",
"The dance that features painted masks, big skirts, heavy jackets, lots of jewellery, and tall headdresses is . - Kathakali.",
"The dance where dancers forms a counterclockwise circle with concentric circles in opposite directions . - Garba dance.",
"Kuchipudi, a Yakshagaana style, conceived by Siddhendra Yogi in . - 17th century.",
"The number of Indian classical dance forms recognized by the Sangeet Natak Academy of India is . - 8.",
"Jhijhiya dance is performed to please the god of rain ‘Indra’ for good rain and crop in . - Bihar.",
"The tribe who performs the Bagurumba folk dance in assam . - Bodo tribe.",
"Grida folk dance is performed in . - Madhya Pradesh.",
"‘Gonph’ is a famous folk dance of . - Goa.",
"Kud, a folk dance, is associated with . - Jammu and Kashmir.",
"Chang Lo tribal dance is performed by the Chang tribe of . - Nagaland.",
"Gunakanta Dutta Borbyan was awarded the Sangeet Natak Akademi Award in . - Sattriya dance.",
"Fugdi dances is performed in . - Goa.",
"Tashi Sabdo dance is associated with . - Sikkim.",
"Agni, Mardana Jhumar, Phagua dances are associated with . - Jharkhand.",
"Koli is the folk dance of . - Maharashtra and Goa.",
"The folk dance ‘Lambadi’ is associated with . - Andhra Pradesh.",
"Chu Faat is a folk dance of . - Sikkim."
]
export const _2 = 
[
"Indian classical dance techniques like Rasa and Bhava trace their origins to . - Bharatmuni's Natyashastra.",
"Lavani, Powada, Koli, Waghya Murali and Dhangari Gaja are folk dance from . - Maharashtra.",
]
export const _3 = 
[
"Indian classical dance techniques like Rasa and Bhava trace their origins to . - Bharatmuni's Natyashastra.",
"3",]